### ISSUE TITLE
Standalone APK?

### ISSUE THREAD

**Issue by eisengrau** [emschu/snmp-cockpit#2]
Hello,

I can see that the app is available on the Play store, but it is possible to have a stand-alone APK at the moment?

Thank You,

**Comment by emschu** [comment]
Dear @eisengrau,

you should now be able to find an .apk file in the [release section](https://github.com/emschu/snmp-cockpit/releases) of this project ;)

In addition, one should consider these remarks:

> As you might know, developing Android apps is pretty time-intensive and it takes a lot of effort to provide you with a stable software, especially if this is related to a technology like SNMP which seems to be pretty dead nowadays.
These are one of the reasons, the Play Store version of this app is not for free as in "free beer", although this is free and libre software as in free speech. Considering the resources (a lot of gigabytes to download, your time, configuration etc.) needed to build an Android App in general, there is a "free" APK version of this app provided here. This file is exactly the same as the Play Store is shipping.
> However if you download and use the following .apk file, you are strongly encouraged (means: it is expected) to provide your honest feedback to the app's authors via e-mail or GitHub issues!
> Further information about feedback channels are provided to you through the app's menu.

Have fun with it and please provide feedback!
